export const FETCH_PLACES = 'FETCH_PLACES'
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS'
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE'

export const FETCH_COORDS = 'FETCH_COORDS'
export const FETCH_COORDS_SUCCESS = 'FETCH_COORDS_SUCCESS'
export const FETCH_COORDS_FAILURE = 'FETCH_COORDS_FAILURE'
